package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class BielletFormController extends BaseController{
	@FXML
	private Label labID;
	@FXML
	private TextField champNom;
	@FXML
	private TextField champPrenom;
	@FXML
	private TextField champTel;
	@FXML
	private ComboBox CombDest;
	@FXML
	private ComboBox CombType;
	@FXML
	private ComboBox CombDep;
	@FXML
	private Label labMontant;
	@FXML
	private Button btnAnnuler;
	@FXML
	private Button btnVF;
	@FXML
	private Button btnValider;

	// Event Listener on ComboBox[#CombDest].onAction
	@FXML
	public void ActCombDest(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#CombType].onAction
	@FXML
	public void ActCopType(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#CombDep].onAction
	@FXML
	public void ActComboDep(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnuler].onAction
	@FXML
	public void annuler(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVF].onAction
	@FXML
	public void valFerm(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnValider].onAction
	@FXML
	public void Valider(ActionEvent event) {
		// TODO Autogenerated
	}
}
