package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableColumn;

public class BilletController {
	@FXML
	private TableColumn col_id;
	@FXML
	private TableColumn col_nom;
	@FXML
	private TableColumn col_prenom;
	@FXML
	private TableColumn col_tel;
	@FXML
	private TableColumn col_dest;
	@FXML
	private TableColumn col_motant;
	@FXML
	private TableColumn col_type;
	@FXML
	private Button btnNewPass;
	@FXML
	private Button btnModif;
	@FXML
	private Button btnDel;
	@FXML
	private ComboBox combTitrePass;
	@FXML
	private TextField champRechPass;
	@FXML
	private Button btnRechPass;
	@FXML
	private Button btnNewResev;
	@FXML
	private Button btnModifResev;
	@FXML
	private Button btnDeletReserv;
	@FXML
	private TableColumn col_id1;
	@FXML
	private TableColumn col_nom1;
	@FXML
	private TableColumn col_prenom1;
	@FXML
	private TableColumn col_tel1;
	@FXML
	private TableColumn col_dest1;
	@FXML
	private TableColumn col_motant1;
	@FXML
	private TableColumn col_type1;
	@FXML
	private ComboBox combRechReserv;
	@FXML
	private TextField champRechReserv;
	@FXML
	private Button btnRechReserv;

	// Event Listener on Button[#btnNewPass].onAction
	@FXML
	public void NewPass(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent parent=FXMLLoader.load(getClass().getResource("BielletForm.fxml"));
			Scene scene=new Scene(parent,600,400);
			Stage stage=new Stage();
			stage.setScene(scene);
			stage.setTitle("Enregistrement de passager");
			stage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	// Event Listener on Button[#btnModif].onAction
	@FXML
	public void modifPss(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDel].onAction
	@FXML
	public void deletePass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechPass].onAction
	@FXML
	public void recherchePass(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewResev].onAction
	@FXML
	public void newReserv(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifResev].onAction
	@FXML
	public void modifReserv(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeletReserv].onAction
	@FXML
	public void deleteReserv(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#champRechReserv].onAction
	@FXML
	public void rechercheReserv(ActionEvent event) {
		// TODO Autogenerated
	}
}

