package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

public class ColisFormController {
	@FXML
	private Label codeColis;
	@FXML
	private TextField nomExp;
	@FXML
	private TextField PrenomExp;
	@FXML
	private DatePicker dateRecep;
	@FXML
	private TextField destination;
	@FXML
	private TextField valeur;
	@FXML
	private TextField TelExp;
	@FXML
	private TextField telDest;
	@FXML
	private TextField prenomDest;
	@FXML
	private TextField nomDes;
	@FXML
	private ComboBox<?> comboDest;
	@FXML
	private TextField frais;
	@FXML
	private Button btnAnnuler;
	@FXML
	private Button btnAnnulerFermer;
	@FXML
	private Button btnValider;

	// Event Listener on Button[#btnAnnuler].onAction
	@FXML
	public void annuler(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnulerFermer].onAction
	@FXML
	public void annulerFermer(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnValider].onAction
	@FXML
	public void valider(ActionEvent event) {
		// TODO Autogenerated
	}
}
