package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class ColisController {
	@FXML
	private Button btnNewColisS;
	@FXML
	private Button btnModifColisS;
	@FXML
	private Button btnSupColisS;
	@FXML
	private ComboBox combTitreColisS;
	@FXML
	private TextField champRechColisS;
	@FXML
	private Button btnRechColisS;
	@FXML
	private Button btnNewColisE;
	@FXML
	private Button btnModifColisE;
	@FXML
	private Button btnSupColisE;
	@FXML
	private ComboBox combTitreColisE;
	@FXML
	private TextField champRechColisE;
	@FXML
	private Button btnRechColisE;
	@FXML
	private Button btnNewCourierS;
	@FXML
	private Button btnModifCourierS;
	@FXML
	private Button btnSupCourierS;
	@FXML
	private ComboBox combTitreCourierS;
	@FXML
	private TextField champRechCourierS;
	@FXML
	private Button btnRechCourierS;
	@FXML
	private Button btnNewCourierE;
	@FXML
	private Button btnModifCourierE;
	@FXML
	private Button btnSupCourierE;
	@FXML
	private ComboBox combTitreCourierE;
	@FXML
	private TextField champRechCourierE;
	@FXML
	private Button btnRechCourierE;

	// Event Listener on Button[#btnNewColisS].onAction
	@FXML
	public void newColisS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifColisS].onAction
	@FXML
	public void modifColisS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupColisS].onAction
	@FXML
	public void supColisS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechColisS].onAction
	@FXML
	public void rechercheColisS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewColisE].onAction
	@FXML
	public void newColisE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifColisE].onAction
	@FXML
	public void modifColisE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupColisE].onAction
	@FXML
	public void supColisE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechColisE].onAction
	@FXML
	public void rechercheColisE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewCourierS].onAction
	@FXML
	public void NewCourierS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifCourierS].onAction
	@FXML
	public void modifCourierS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupCourierS].onAction
	@FXML
	public void supprimeCourierS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechCourierS].onAction
	@FXML
	public void rechercheCourierS(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewCourierE].onAction
	@FXML
	public void newCourierE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifCourierE].onAction
	@FXML
	public void modifCourierE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupCourierE].onAction
	@FXML
	public void supprimeCourierE(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechCourierE].onAction
	@FXML
	public void rechercheCourierE(ActionEvent event) {
		// TODO Autogenerated
	}
}
