package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class CompteController {
	@FXML
	private TextField mail;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private PasswordField pwd;
	@FXML
	private PasswordField confPwd;
	@FXML
	private Button btnValider;
	@FXML
	private Button btnAnuler;

	// Event Listener on Button[#btnValider].onAction
	@FXML
	public void valider(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnuler].onAction
	@FXML
	public void annuler(ActionEvent event) {
		// TODO Autogenerated
	}
}
