package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import metiers.Utilisateur;

import java.net.URL;
import java.util.ResourceBundle;

import DataBase.UtilisateurDAO;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class CompteController implements Initializable{
	@FXML
	private TextField mail;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private PasswordField pwd;
	@FXML
	private PasswordField confPwd;
	@FXML
	private Button btnValider;
	@FXML
	private Button btnAnuler;

	// Event Listener on Button[#btnValider].onAction
	@FXML
	public void valider(ActionEvent event) {
		if(!(mail.getText().equals("")|| nom.getText().equals(""))) {
			UtilisateurDAO userDAO=new UtilisateurDAO();
			if(UtilisateurDAO.userCourent!=null) {
				UtilisateurDAO.userCourent.setMail(nom.getText());
				UtilisateurDAO.userCourent.setNomUt(mail.getText());
				UtilisateurDAO.userCourent.setMotdepasse(pwd.getText());
				Utilisateur user =userDAO.update(UtilisateurDAO.userCourent);
				int i =UtilisateursController.ListeUtilisateur.indexOf(UtilisateurDAO.userCourent);
				UtilisateursController.ListeUtilisateur.remove(UtilisateurDAO.userCourent);
				UtilisateursController.ListeUtilisateur.add(i, user);
				
				UtilisateurDAO.userCourent=null;
			}else {
				Utilisateur user= userDAO.create(new Utilisateur());
				UtilisateursController.ListeUtilisateur.add(user);
				mail.setText("");
				nom.setText("");
				pwd.setText("");
			}
			
			
		}
		
		
	}
	// Event Listener on Button[#btnAnuler].onAction
	@FXML
	public void annuler(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		if(UtilisateurDAO.userCourent!=null) {
			mail.setText(UtilisateurDAO.userCourent.getMail());
			nom.setText(UtilisateurDAO.userCourent.getNomUt());
			pwd.setText(UtilisateurDAO.userCourent.getMotdepasse());
		}
		
	}
}
