package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class LignesTransController {
	@FXML
	private TableView TableDepart;
	@FXML
	private TableColumn col_id1;
	@FXML
	private TableColumn col_code;
	@FXML
	private TableColumn col_jour;
	@FXML
	private TableColumn col_heure;
	@FXML
	private TableColumn col_dest;
	@FXML
	private TableColumn col_nbPlcs;
	@FXML
	private ComboBox combTitreDepart;
	@FXML
	private TextField champRechDepart;
	@FXML
	private Button btnRechDepart;
	@FXML
	private Button btnNewDepart;
	@FXML
	private Button btnModifDepart;
	@FXML
	private Button btnSupDepart;
	@FXML
	private TableView TableVille;
	@FXML
	private TableColumn col_id;
	@FXML
	private TableColumn col_ville;
	@FXML
	private TableColumn col_distance;
	@FXML
	private TableColumn col_TPA;
	@FXML
	private TableColumn col_TPAR;
	@FXML
	private TableColumn col_Tcourier;
	@FXML
	private Button btnNewVille;
	@FXML
	private Button btnModifVille;
	@FXML
	private Button btnsuVille;
	@FXML
	private ComboBox combTitreVille;
	@FXML
	private TextField champRechVille;
	@FXML
	private Button btnRechVille;

	// Event Listener on Button[#btnRechDepart].onAction
	@FXML
	public void rechercheDepart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewDepart].onAction
	@FXML
	public void newDepart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifDepart].onAction
	@FXML
	public void modifDpart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupDepart].onAction
	@FXML
	public void supDapart(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNewVille].onAction
	@FXML
	public void newVille(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnModifVille].onAction
	@FXML
	public void modifVille(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnsuVille].onAction
	@FXML
	public void supVille(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRechVille].onAction
	@FXML
	public void rechercheVille(ActionEvent event) {
		// TODO Autogenerated
	}
}
