package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import metiers.Ligne;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class LigneController implements Initializable{
	@FXML
	private TableView<Ligne> tableLinge;
	@FXML
	private TableColumn<Ligne,Long> col_id;
	@FXML
	private TableColumn<Ligne,String> col_nom;
	@FXML
	private Button btnValide;
	@FXML
	private Button btnModif;
	@FXML
	private Button btnSupprime;
	@FXML
	private TextField nomVille;

	// Event Listener on Button[#btnValide].onAction
	@FXML
	public void valide(ActionEvent event) {
		
	}
	// Event Listener on Button[#btnModif].onAction
	@FXML
	public void modif(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupprime].onAction
	@FXML
	public void supprime(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
