package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class MenuController extends BaseController{
	@FXML
	private Button brnAc;
	@FXML
	private Button btnBil;
	@FXML
	private Button btnColis;
	@FXML
	private Button btnStat;
	@FXML
	private Button btnUsers;
	@FXML
	private Button btnQuit;
	@FXML
	private BorderPane PanePrincipal;
	
	Object[] Pages= new Object[10];
	// Event Listener on Button[#brnAc].onAction
	@FXML
	public void accueil(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBil].onAction
	@FXML
	public void biellet(ActionEvent event) {
		// TODO Autogenerated
		if(Pages[1]==null) {
			try {
				Parent root=FXMLLoader.load(getClass().getResource("Billet.fxml"));
				Pages[1]=root;
				PanePrincipal.setCenter((Node) Pages[1]);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}else {PanePrincipal.setCenter((Node) Pages[1]);}
		
		
	}
	// Event Listener on Button[#btnColis].onAction
	@FXML
	public void colis(ActionEvent event) {
		// TODO Autogenerated
		
		if(Pages[2]==null) {
			try {
				Parent root=FXMLLoader.load(getClass().getResource("Colis.fxml"));
				Pages[2]=root;
				PanePrincipal.setCenter((Node) Pages[2]);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}else {PanePrincipal.setCenter((Node) Pages[2]);}
		
	}
	// Event Listener on Button[#btnStat].onAction
	@FXML
	public void stat(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnQuit].onAction
	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
		getMainApp().afficherPage("Connexion.fxml", "Connexion",0);
		
	}
}
