package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;


import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.layout.BorderPane;

public class MenuController<JFXButton> extends BaseController implements Initializable{
	
	@FXML
	private BorderPane PanePrincipal;
	
	 @FXML
	 private JFXButton brnAc;

	 @FXML
	 private JFXButton btnBil;

	 @FXML
	 private JFXButton btnColis;

	 @FXML
	 private JFXButton btnParam;

	 @FXML
	 private JFXButton btnProg;

	 @FXML
	 private JFXButton btnQuit;

	 @FXML
	 private JFXButton btnStat;

	 @FXML
	 private JFXButton btnUsers;

	
	Object[] Pages= new Object[10];
	// Event Listener on Button[#brnAc].onAction
	
	//initialisation du tableau de bord au lancement
	
	
	
	 @FXML
	 void accueil(ActionEvent event) {
	    	if(Pages[1]==null) {
				try {
					Parent root=FXMLLoader.load(getClass().getResource("DashBoard.fxml"));
					Pages[1]=root;
					PanePrincipal.setCenter((Node) Pages[1]);
				} catch (IOException e) {
					e.printStackTrace();
				}
				
			}else {PanePrincipal.setCenter((Node) Pages[1]);}
			
	    }
	// Event Listener on Button[#btnBil].onAction
	@FXML
	public void biellet(ActionEvent event) {
		
		if(Pages[2]==null) {
			try {
				Parent root=FXMLLoader.load(getClass().getResource("Billet.fxml"));
				Pages[2]=root;
				PanePrincipal.setCenter((Node) Pages[2]);
			} catch (IOException e) {
				
				e.printStackTrace();
			}
			
		}else {PanePrincipal.setCenter((Node) Pages[2]);}
		
		
	}
	@FXML
	public void user(ActionEvent event) {
	    	if(Pages[3]==null) {
				try {
					Parent root=FXMLLoader.load(getClass().getResource("Utilisateurs.fxml"));
					Pages[3]=root;
					PanePrincipal.setCenter((Node) Pages[3]);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
			}else {PanePrincipal.setCenter((Node) Pages[3]);}
	    }
	    

	  @FXML
	  public void colis(ActionEvent event) {
	    	if(Pages[4]==null) {
				try {
					Parent root=FXMLLoader.load(getClass().getResource("Colis.fxml"));
					Pages[4]=root;
					PanePrincipal.setCenter((Node) Pages[4]);
				} catch (IOException e) {
					
					e.printStackTrace();
				}
				
			}else {PanePrincipal.setCenter((Node) Pages[4]);}
	    }

	@FXML
	public void program(ActionEvent event) {
		if(Pages[5]==null) {
			try {
				Parent root=FXMLLoader.load(getClass().getResource("Lignes Trans.fxml"));
				Pages[5]=root;
				PanePrincipal.setCenter((Node) Pages[5]);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}else {PanePrincipal.setCenter((Node) Pages[5]);}
	}
	@FXML
	public void param(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnQuit].onAction
	
	@FXML
	public void quitter(ActionEvent event) {
		// TODO Autogenerated
		//getMainApp().parents[0]=null;
		getMainApp().afficherPage("Connexion.fxml", "Connexion");
		
	}


	@FXML
	void stat(ActionEvent event) {

	}
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		try {
			Parent root=FXMLLoader.load(getClass().getResource("DashBoard.fxml"));
			Pages[1]=root;
			PanePrincipal.setCenter((Node) Pages[1]);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}

