package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import metiers.Billet;
import metiers.Destination;
import outils.Outils;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class RecuController implements Initializable {
	@FXML
	private TableView<Billet> tableLinge;
	@FXML
	private TableColumn<Billet,Long> col_id;
	@FXML
	private TableColumn<Billet,String> col_ville;
	@FXML
	private TableColumn<Billet,Double> col_TA;
	@FXML
	private TableColumn<Billet,Double> col_TAR;
	@FXML
	private TableColumn<Billet,Double> col_TARC;
	@FXML
	private Button btnModif;
	@FXML
	private Button btnSupprime;
	@FXML
	private Button btnValide;
	@FXML
	private Button btnAnnule;
	
	@FXML
	private Button btnFerme;
	@FXML
	private ComboBox<Destination> comboDest;
	@FXML
	private TextField TAR;
	@FXML
	private TextField TA;
	@FXML
	private TextField TC;

	// Event Listener on Button[#btnModif].onAction
	@FXML
	public void modif(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSupprime].onAction
	@FXML
	public void supprime(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnValide].onAction
	@FXML
	public void valide(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnule].onAction
	@FXML
	public void Annuler(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void fermer(ActionEvent event) {
		if(Outils.confirmer("Voullez vous vraiment fermer cette fenetre?")) {
			Stage stage=(Stage)btnFerme.getScene().getWindow();
			stage.close();
		}
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
	
	
}
